volumes:
  rabbitmq_data:

services:
  ####################################
  # RabbitMQ: The messaging broker
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ####################################
  # App
  ####################################
  foodsub:
    build:
      context: ./
      dockerfile: Dockerfile
    image: food-sub:1.0
    # restart: always
    depends_on:
      - rabbitmq
    env_file:
      - "dev.env"
